security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'bcrypt'

    providers:
        users_in_memory:
            memory:
                users:
                    api_viewer: { password: '$2y$13$OrzG/CDwIrPUbor6BH7.B.bLGOjJTxh3t/Bhs8gbGLL5chFrgpufq', roles: ['ROLE_API'] }

    firewalls:
        api_doc:
            pattern: ^/api/doc
            provider: users_in_memory
            http_basic: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users_in_memory

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/profile, roles: ROLE_USER }
