version: "3.3"

services:
  db:
    image: "mysql:8"
    container_name: "storage_mysql"
    ports:
      - "3306:3306"
    networks:
      - storage-network
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: storage_local
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    networks:
      - storage-network
    volumes:
      - "./../public:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
    - '80:80'
    depends_on:
      - php

  php:
    build:
      context: ./..
      dockerfile: docker/php/Dockerfile
    volumes:
      - './../:/var/www/html'
    restart: on-failure
    container_name: "storage-backend"
    networks:
      - storage-network
    env_file:
      - .env
    user: 1000:1000

networks:
  storage-network:

volumes:
  db_data: {}
